<a href="https://colab.research.google.com/github/yvrjsharma/Pytorch/blob/main/PytorchBook1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
a = torch.ones(3) #1 dim vector of size 3
a[1], type(a[1]), float(a[1])

(tensor(1.), torch.Tensor, 1.0)

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [10]:
a =  torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [12]:
a = torch.zeros(3,2)
a, a.shape, a[]

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]), torch.Size([3, 2]))

In [14]:
a =  torch.tensor([[1.,2.],[3.,4.],[5.,6.]])
a, a.shape, a[0,1], a[0]

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]), torch.Size([3, 2]), tensor(2.), tensor([1., 2.]))

In [20]:
a[1:], a[1:,0], a[None]

(tensor([[3., 4.],
         [5., 6.]]), tensor([3., 5.]), tensor([[[1., 2.],
          [3., 4.],
          [5., 6.]]]))